### ISSUE TITLE
1.1.0 is a major breaking change

### ISSUE THREAD

**Issue by mgcrea** [substack/stream-combiner2#6]
I'm using stream-combiner2 in a lot of complex gulp transforms that I'm using to serve/build angular applications. It looks like that the `end` event is not properly propagated anymore. For instance, this [stream combination](https://github.com/ng-tools/factory-angular2-channels/blob/v0.8.6/lib/channels/index/src.js#L19) is never properly ended since the 1.1.0 release.

**Comment by apierzch** [comment]
It breaks my build as well, have a look at this task definition:
```
gulp.task('vendorJS', function () {
    return gulp.src(vendorJS)
        .pipe(combiner(
            concat('vendor.min.js'),
            uglify()
        ))
        .pipe(gulp.dest('./build/dist/vendor'));
});
```
After upgrading stream-combiner2 it fails with following error:

```
[13:06:56] Starting 'vendorJS'...
events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: Invalid non-string/buffer chunk
    at validChunk ([my-project-path]/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_writable.js:217:14)
    at DuplexWrapper.Writable.write ([my-project-path]/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_writable.js:244:12)
    at write ([my-project-path]/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow ([my-project-path]/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable ([my-project-path]/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:104:17)
    at emitReadable_ ([my-project-path]/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable ([my-project-path]/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk ([my-project-path]/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push ([my-project-path]/node_modules/readable-stream/lib/_stream_readable.js:149:10)
```

**Comment by AlbertoElias** [comment]
I get the same error, raised in [this issue](https://github.com/Financial-Times/origami-build-tools/issues/325)

**Comment by mgcrea** [comment]
@apierzch looks like you should use `combiner.obj`.
